name: CI/CD Workflow for QuickThrift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install ESLint
      - name: Install ESLint
        run: npm install eslint --save-dev

      # Step 4: Run ESLint
      - name: Run ESLint
        run: npx eslint . --ext .js

  html-check:
    name: Check HTML for Broken Links
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install HTMLProofer
      - name: Install HTMLProofer
        run: sudo gem install html-proofer

      # Step 3: Run HTMLProofer
      - name: Check HTML
        run: htmlproofer ./ --allow-hash-href --file-ignore /node_modules/

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
